version: "3.8"

services:
  allariwebcraft-mvc:
    build:
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - allariwebcraft-service

  allariwebcraft-service:
    build:
      dockerfile: Dockerfile
